client/.eslintrc.json
client/src/components/AccessibilityStatement.jsx
client/src/components/__snapshots__/AccessibilityStatement.test.jsx.snap

• Allow import of dev dependencies
• Fix quotes to be smart
• Update package.json and lock file
• Minor linting

Fix linting

---

client/src/pages/cases/CasePage.jsx
client/src/pages/cases/CasePage.test.jsx
client/src/pages/cases/routes.js
client/src/routes/index.js
client/src/routes/route.test.js

In this PR
- create a page for 'case'
- add test for case page loads
- add a route to /case
- update test for route

COP-3202 Add route for case page

---

client/public/locales/en-GB/translation.json
client/src/App.jsx
client/src/pages/home/components/Card.jsx
client/src/pages/home/components/Card.test.jsx
client/src/pages/home/components/_card.scss
client/src/pages/home/index.jsx
client/src/pages/home/index.test.jsx
client/src/pages/reports/ReportsListPage.jsx
client/src/pages/reports/ReportsListPage.scss
client/src/pages/reports/ReportsListPage.test.jsx
client/src/pages/reports/routes.js
client/src/pages/reports/routes.test.js
client/src/routes/index.js
client/src/routes/route.test.js
server/src/main/resources/application.yml

• Add routing and card for Reports
• Retrieve list of reports from Reporting Service
• Some formatting/heading fixes

Enable reports listing

---

.drone.yml
README.md

Updates after discussion with Anil
- removed the badge from README as it's not reflective of this repo
- increased deploy timeout to 8m, because it was showing that it had not completed deployment when it actually had

Setup updates

---

client/src/components/header/index.jsx
client/src/components/header/index.test.jsx
client/src/routes/index.js
client/src/routes/route.test.js

Revert dashboard url from `/dashboard` to `/`

COP-2793 Update header, product name and link to dashboard

---

client/src/pages/forms/FormPage.jsx

Moved functions back inside UseEffect as the build for master was failing due to them being outside

COP-3774 multistep forms

---

client/src/pages/forms/FormPage.jsx

Removing the isMounted check from the nextStep form loading
Commenting out alertContext for the time being to remove the if statement until we know form is loading correctly
Adding console logs to track data at various states

COP-3774 Remove isMounted check, alertContext, add tracking

---

client/src/pages/forms/FormPage.jsx

Reverts UKHomeOffice/cop-ui#60

Revert "COP-3774 Remove isMounted check, alertContext, add tracking"

---

client/src/pages/forms/FormPage.jsx

Reverts UKHomeOffice/cop-ui#59

Revert "COP-3774 multistep forms"

---

client/src/components/AccessibilityStatement.jsx
client/src/components/__snapshots__/AccessibilityStatement.test.jsx.snap

- Use config property for support URL
- Add changes as in UI V1 (including further edits)

Update accessibility statement

---

client/src/pages/tasks/TaskPage.jsx

User can click the business key and have the related case open in a new tab
Added link
- click on any task
- click on the businessKey at the top of the screen
> - you should be taken to /cases/<businessKey>

COP-2825 Link to case

---

client/src/pages/tasks/TaskPage.jsx

Add currentUser to dependencies and remove translation from within useEffect

COP-2822 Dependencies

---

client/src/components/AccessibilityStatement.jsx
client/src/components/__snapshots__/AccessibilityStatement.test.jsx.snap

Rename EU Transition form to be Record Trade Checks

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/pages/reports/ReportsListPage.jsx
client/src/pages/reports/components/PowerBIReport.jsx
server/src/main/java/io/digitalpatterns/workflow/ui/UIConfig.java

This is first steps to getting Matomo tracking up and running across the application. We should see Reports list and pages tracked, and if we do then we'll look at adding other sections.

Implement Matomo tracking

---

client/package-lock.json
client/package.json

Fixes issue with Husky not running with GUI Git clients.

Downgrade Husky

---

client/src/components/form/DisplayForm.test.jsx

Likely due to async issues, will investigate and re-add later

Remove test that requires navigate as it's sporadically failing

---

client/src/pages/forms/FormPage.jsx
client/src/pages/forms/FormPage.test.jsx

Also refactor code and tests somewhat: improve destructuring, rename functions, remove conditionals, remove unnecessary "then" callback.

Set document title from process name

---

client/public/locales/en-GB/translation.json
client/src/pages/cases/CaseDetailsPanel.jsx
client/src/pages/cases/CasePage.jsx
client/src/pages/cases/CasesPage.scss
client/src/pages/cases/CasesResultsPanel.test.jsx
client/src/pages/cases/components/CaseHistory.jsx
client/src/pages/cases/components/CaseHistory.test.jsx
client/src/pages/cases/components/CaseMetrics.jsx
client/src/pages/cases/components/CaseMetrics.test.jsx
client/src/pages/cases/components/FormDetails.jsx

**Description**
This branch adds the functionality to view case metrics when a case is selected. It also updates some of the tests to allow for this change. 
**To test:**
- Pull branch and run locally in development mode, making sure you are using the cop-dev proxy in the package.json.
- Search for any case and select from the list. 
- Under Case metrics drop down you should find the relevant information about the case.

COP-2834: View Case metrics 

---

client/src/components/form/DisplayForm.jsx

A user should be able to submit a form with nested forms successfully
- Added `Formio.registerPlugin()` in order to interpolate nested forms with context properly
- Moved reformatted `keycloakContext` object out into separate variable as it is used multiple times
- Pull and run cop locally pointing the proxy to the dev environment
- Login
- Select form with nested forms (NS referral)
- Click 'next'
- *You should see the `port` dropdown prefill*
- Click the `Mode of transport` dropdown
- *You should see a list of mode of transports*
- Complete rest of form
- *You should be able to submit the form successfully*

COP-5060 Interpolate nested forms and DisplayForm refactor

---

kube/deployment.yml
kube/ingress.yml
kube/network-policy.yml
kube/service.yml

modified:   kube/deployment.yml
modified:   kube/ingress.yml
modified:   kube/network-policy.yml
modified:   kube/service.yml

cop-5610 remove nginx-proxy

---

server/src/main/resources/logback-spring.xml

We are receiving an error from the Zuul proxying when we upload large files.
Updating logging to see if we can get more information from it
We can't upload files locally due to auth issues, so need to test this on dev

Update logging to see if we can get more information

---

server/src/main/resources/logback-spring.xml

Return logging to the nicely formatted version

Return logging to original form now testing is complete

---

client/src/pages/tasks/components/TaskPageSummary.jsx

Understand & fix `existingSubmission` as it is prefilling data on forms in unexpected ways
This PR is to put back the assigneeText after removing it from TaskPage in PR145
Added check where we display assigneeText to determine whether to show assignee email, or current assignee message
- open a task assigned to you
- > you should see text that `You are the current assignee` in the `assignee` section
- open a task not assigned to you (don't claim it)
- > you should see the email address of who that task is assigned to in the `assignee` section
- open an unassigned task (e.g enhance intel)
- > you should see text that says `Unassigned` in the `assignee` section

COP-5557 Set assignee text based on current user or not

---

client/src/pages/tasks/TaskPage.jsx

This PR reverts most of the refactoring from https://github.com/UKHomeOffice/cop-ui/pull/145
This is because we've discovered that to fix the bug that PR 145 was a first piece of, is much larger than hoped and so it has been moved to v2.1.
We're retaining the change to where the `assigneeText` is set as that resolved a different issue.
- check collect-event-at-border
- > you should have follow on forms load correctly
- > you should be able to add attachments
- > you should be able to submit the final form
- > you should be able to see it completed in Cockpit
- check submit intel referral
- > you should be able to complete the form
- > you should see an enhance task in group tasks
- > you should be able to claim and complete that enhance task
- > you should be able to see it completed in …

COP-5557 - Revert the refactoring of TaskPage (keep assignee changes)

---

client/package-lock.json
client/package.json
client/src/components/form/DisplayForm.jsx
client/src/pages/cases/components/CaseAction.jsx
client/src/pages/cases/components/FormDetails.jsx

This branch updates the formio-gds-template package from "@digitalpatterns/formio-gds-template" to "@ukhomeoffice/formio-gds-template" as this has now been published as a UK Homeoffice version.

COP-5801: Update formio-gds-template package

---

client/package-lock.json
client/package.json

Upgrading formio-gds-template to remove z-index bug

Upgrade formio-gds-template to 1.0.3

---

client/src/components/PrivacyAndCookiePolicy.jsx
client/src/components/__snapshots__/PrivacyAndCookiePolicy.test.jsx.snap

Updates policy to match one at www.

Update Privacy Policy

---

client/src/components/form/DisplayForm.jsx
client/src/components/form/DisplayForm.test.jsx

Scroll page to the top on errors

---

client/src/pages/tasks/components/TaskPageSummary.jsx
client/src/pages/tasks/components/TaskPageSummary.test.jsx
client/src/pages/tasks/components/__snapshots__/TaskPageSummary.test.jsx.snap

As in v1. Also add snapshot test for this file.

Use H1 for task heading

---

client/src/components/footer/index.jsx
client/src/components/footer/index.test.jsx
client/src/components/header/index.jsx
client/src/components/header/index.test.jsx

Align support links with GDS recommendations

---

client/src/components/form/DisplayForm.jsx
client/src/pages/cases/components/CaseAttachments.jsx
client/src/pages/cases/components/CaseAttachments.test.jsx
server/src/main/resources/application.yml

Reverts UKHomeOffice/cop-ui#189

Revert "remove the additional /files from DisplayForm.jsx, CaseAttachments.js…"

---

client/src/pages/home/index.jsx

This ticket was inexplicably withdrawn, but the issue is easily fixed.

Fix React warning
