UKHomeOffice/cop-ui

client/public/locales/en-GB/translation.json, client/src/components/AccessibilityStatement.jsx, client/src/components/PrivacyAndCookiePolicy.jsx, client/src/components/__snapshots__/AccessibilityStatement.test.jsx.snap, client/src/components/__snapshots__/PrivacyAndCookiePolicy.test.jsx.snap, client/src/components/alert/ApiErrorAlert.jsx, client/src/components/alert/SubmissionSuccessAlert.jsx, client/src/pages/forms/FormsListPage.jsx, client/src/pages/forms/FormsListPage.test.jsx, client/src/pages/home/index.jsx, client/src/pages/tasks/TasksListPage.jsx
Set headings to be from H1 large downward. Also:
• Minor tweaks to API error message formatting
• Set user's name on dashboard to Keycloak name
• Render main headings as h1, subheadings as captions
=> Adjust headings

client/public/locales/en-GB/translation.json, client/src/components/header/index.jsx, client/src/components/header/index.test.jsx
User should be able to navigate to `forms/edit-your-profile` by clicking the My profile navigation link in the header.
- Updated header/index.jsx to have a My profile `NavLink` 
- en-GB/translation.json has been updated to contain a `my-profile` prop inside the `header` prop
- Added assertion to header/index.test.jsx for the above AC
- `navigation.navigate()` used for navigation instead of standard `href` in NavLink. This is done as obtaining the edit-your-profile form is asynchronous
- Currently, there is no `edit-your-profile` functionality and so this navigates to an empty page
- Pull and run cop-ui
- Login to cop-ui
- Click 'My profile' in the header
- You should be navigated to the `forms/edit-your-profile` page
- If you click on the `My profile` whilst on the …
=> COP-2794 Add nav link to My profile

server/src/main/resources/application.yml
Confirmed with Anil, we need to use `referenceDataUrl` as the variable as this is what the form api looks for. He's updated secrets as well
=> Update reference data variable to match form api

client/public/locales/en-GB/translation.json, client/src/pages/cases/CasePage.jsx, client/src/pages/cases/CasesPage.scss, client/src/pages/cases/CasesResultsPanel.jsx
Cases page should show the default page styling, without functionality
- Removed `<strong>` in favour of GDS class for bold text
- Added the search panels
- Updated titles
- The search box and number of cases are not functional, once the styling is signed off they will be commented out until the functionality is added
- Pull and run cop-ui
- Login to cop-ui
- Go to /cases
- You should see the titles, search box, and search results panels
=> COP-2826 Caseview skeleton

client/src/components/header/index.jsx, client/src/index.scss
The phase banner should stretch the full width of the page and there should be no space between the top of the page and the top of the phase banner
- Added margin of 0px to the body
-  Changed the feedback url in header/index.jsx to point towards the correct feedback url
- Pull and run cop-ui
- Login
- Click on the feedback link in the header, this should take you to https://support.cop.homeoffice.gov.uk/servicedesk/customer/portal/3/create/54
- You should not see any margin on top of and to the side of the phase banner
=> COP-2796 Update Phase Banner

server/src/main/resources/application.yml
Confirmed with Mark we should use refData.url
Testing implications on dev once this is merged to see how it will impact existing forms
=> Revert refdata variable

cases/CasePage.jsx, cases/routes.js, client/public/locales/en-GB/translation.json, client/src/pages/cases/CaseDetailsPanel.jsx, client/src/pages/cases/CasePage.jsx, client/src/pages/cases/components/CaseActions.jsx, client/src/pages/cases/components/CaseAttachments.jsx, client/src/pages/cases/components/CaseHistory.jsx, client/src/pages/cases/components/CaseIntro.jsx, client/src/pages/cases/components/CaseMetrics.jsx, client/src/pages/cases/routes.js
Default details panel should exist for when there is no case for the businessKey specified
- moved sections to their own components
- moved content to translations.json
- The h3 on the intro is hardcoded to 'Cases' for now, functionality will be added to make it the businessKey
- Pull and run cop-ui
- Login to cop-ui
- Navigate to the /cases page without error
- The page should still contain the case actions, history, attachment, metrics sections
- There should be no instances of `pages.cases.xxx`, all should be user friendly words
=> COP-2826 Split details into components

client/src/components/form/DisplayForm.jsx, client/src/components/form/DisplayForm.scss
*Bug*
When viewing /forms we were seeing a narrow header, it was using the GDS 1020px version rather than the COP 1400px version. Looked to be due to the DisplayForms component.
*Updated*
Added override css for that component
=> COP-3590 Add override scss for header when displaying form

client/src/components/form/DisplayForm.scss, client/src/pages/tasks/components/TaskList.scss
Header is correctly formatted on the /tasks page
- Defined the govuk-page-width variable at the top of the TaskList.scss file and set it to 1400px
- Changed fix value in DisplayForm.scss to govuk-page-width variable
=> COP-3591 Fix header on tasks

client/public/locales/en-GB/translation.json, client/src/pages/home/components/Card.jsx, client/src/pages/home/index.jsx, client/src/pages/home/index.test.jsx
User should be able to click on a cases panel on the dashboard that takes them to the /cases url
- Updated translation.json to contain content for cases
- Card title rendering now includes a condition to check if there is both a count and title to display, if so then render both items accordingly. If this this combination is not present then only render the title provided (Forms, Cases, Reports)
- Added default values for Card props that are now not required to be passed down, this is done to allow for the conditional check mentioned above.
- Removed axios call in home/index.jsx that returns the number of forms available to the user, this is does not appear on COP on the dashboard and so has been removed.
- Changed jsx in home/index.jsx to be in accordance with the existing cop's ui, …
=> COP-2819 Add Cases box

client/src/components/form/DisplayForm.jsx
This composes an `environmentContext` object for forms with the required proxy paths for them to be able to load data. This object is sent for interpolation and merged with any existing form submission object.
=> Add environmentContext

client/src/pages/forms/hooks.js, client/src/pages/forms/hooks.test.jsx
User should be able to click on a cases panel on the dashboard that takes them to the /cases url
- Added `initiatedBy` as a variable to the `submit` function for forms
- set value to be the email address of the submitting user
- Our BPMNs use `initatedBy` to assign the task
- As our BPMNs/Forms currently use shift and staff details that are unavailable at the moment, you can currently only test this with a flow that does not require them (negative border event)
*COP UI local:*
- Remove the `group` from collect-event-at-border.bpmn negative element (it uses shiftDetails which does not exist)
- Pull and run cop-ui local with new gradle build
- Login to cop-ui
- Submit a `record-border-event` `negative` flow
- It should submit without error
=> Add initiatedBy variable to track user email who submitted the form

client/src/pages/forms/FormPage.jsx, client/src/pages/forms/FormPage.test.jsx
**AC**
Forms should have a page title (based off the `name` in the data, which is set in the related BPMN. This goes above the form's steps.
**Updated**
Added API call to get the `name` and set it as the `<h1>`
**To test**
- click on `record border event` form
- you should see
- Page Title: `Collect event at border`
- Form Title: `Record the details of a border event`
=> COP-3613 Add page title for forms

client/public/locales/en-GB/translation.json, client/src/components/NotFound.jsx, client/src/components/__snapshots__/NotFound.test.jsx.snap, client/src/components/alert/ApiErrorAlert.jsx, client/src/components/layout/index.jsx, client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/routes.js
**Updated**
- move object keys to be ordered by common, then pages by alphabetical
- update tasks keys and wording to match what we use in v1
- add group tasks keys and wording
**To test**
- open cop-ui
- click through pages
>- there should be no instances of text looking like `task.list.heading`
>- all titles should be readable
>- task box on dashboard and /tasks should match what is seen in cop v1
=> COP-3722 Content

client/src/pages/home/index.jsx, client/src/pages/home/index.test.jsx, client/src/pages/tasks/routes.js
**AC**
Add the group task panel, design and text as per cop v1
**Notes**
- Content was added to translate.json in previous PR
- Page titles have not been updated for these pages, that will be done later
**Updated**
- added panel
- added /tasks/yours as the url for your tasks
- updated dashboard links & tests
**To test**
- view dashboard (/)
> you should see a panel for your tasks
> you should see a panel for group tasks
- click on your tasks
> you should be taken to /tasks/yours
- go back to dashboard
- click on group tasks
> you should be taken to /tasks
=> COP-3722 Add group tasks to dashboard and create list page for your tasks

client/.eslintrc.json, client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/components/TaskFilters.jsx, client/src/pages/tasks/components/TaskFilters.test.jsx, client/src/pages/tasks/routes.js
Add filter bar to task list
- Added a prop to pass down to `your-tasks` and `tasks` routes in `task/routes.js`, it passes a string down to the route to distinguish between task list content
- Created `TaskFilter` component for the task list page
- The filter bar is not functional currently, it will be implemented fully later
- Need to change rendered tasks design in a later PR
- Pull and run cop-ui locally
- Login
- Navigate to `/tasks`:
- You should see the dropdown selectors without error
- Select different options on the dropdowns
- You should not see any changes to the tasks displayed on screen
- Navigate to `/tasks/your-tasks`:
- You should see the dropdown selectors without error
- Select different options on the dropdowns
- You should not see any changes to the tasks displayed on …
=> COP-3765 Add task filter bar to task list

client/package-lock.json, client/package.json, client/src/pages/tasks/components/TaskList.jsx, client/src/pages/tasks/components/TaskList.test.jsx, client/src/pages/tasks/components/TaskListItem.jsx, client/src/pages/tasks/components/TaskListItem.scss, client/src/pages/tasks/components/TaskListItem.test.jsx
The tasks list page design should be the same as COPv1 UI task list page
- Added dayjs package, this is due to momentjs not being maintained anymore and has recommended a switch to a new package (dayjs being a suggestion)
- Refactored TaskList.jsx removing large chunks of jsx and moved them out to separate files (TaskListItem.jsx)
- Added TaskListItem.jsx to handle rendering each individual task
- Added initial tests for TaskListItem.jsx
- The functionality is still limited (can't claim task, different grouping, sorting, search etc) as this ticket is for setting up the design, further functionality will be added in later PRs
- Business key is not returned from tasks api call and so the task id is being used as a placeholder for now
- Login
- Navigate to /tasks
- …
=> COP-3765 task list design

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/components/TaskFilters.jsx, client/src/pages/tasks/components/TaskFilters.test.jsx, client/src/pages/tasks/components/TaskListItem.jsx
User is able to sort tasks by due date, created date, and priority
- Set the default values for sorting and grouping to be the same as COPv1 UI
- Added `sorting` to json body request to cop-service
- Only trigger api call to cop-service when sorting and search have been used, not grouping
- Changed `TaskFilters.jsx` option values to match the format in the camunda API docs
- Added more tests to `TaskFilters.jsx` 
- Group by and search functionality have not been added yet
- Pull and run cop-ui locally (spin up docker containers etc.)
- Login
- If you have already submitted forms and have tasks then skip the next step
- Submit at least 2 forms (record border event can be submitted pending form changes, this may require making officer details not mandatory in order to complete the form and …
=> COP-2808 Sort tasks by due date/created date/priority

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/TasksListPage.test.jsx, client/src/pages/tasks/components/TaskFilters.jsx, client/src/pages/tasks/components/TaskList.jsx, client/src/pages/tasks/components/TaskList.test.jsx, client/src/pages/tasks/components/TaskListItem.jsx, client/src/pages/tasks/components/TaskListItem.test.jsx, client/src/pages/tasks/routes.js, client/src/pages/tasks/utils.js
Users should be able to group tasks by category, bf reference (business key), priority and assignee
- Added api call to `/process-instance` to associate a business key with each task and updated `TaskListPage.test.jsx` to reflect the extra call
- Refactored `TaskListPage.test.jsx` slightly moving `mockData` higher in scope so other tests can access it (given more assertions will be added - they will)
- Added assertions to test grouping in `TaskListPage.test.jsx`
- Updated `TaskFilters.jsx` bf reference option value to `businessKey` as this matches the property name in the reponse returned in the `/process-instance` call
- Passed `groupBy` state to `TaskList` and created the task groupings dynamically
- Changed pluralisation of task depending on number of tasks in the rendered groups
- …
=> COP-2809 Group tasks visually by category/BF ref/priority/assignee

client/.eslintrc.json, client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/TasksListPage.test.jsx, client/src/pages/tasks/components/TaskList.jsx
User is able to search for a task by name
### Updated
- Split out `data` state in order keep only directly related data together i.e. maxResults is now a constant as it's value never changed
- Added `filter.search` to request payload to both `tasksResponse` and `taskCountResponse` to allow for search functionality
- Added `taskTypePayload` which decides the type of tasks to search for (either your tasks or your teams tasks)
- Swapped the group name and number of tasks in each group around to match COPv1 UI
- API calls on the dashboard need to be revisited for the task count to ensure they are accurate and reflective of their respective task counts
- Pull and run cop-ui locally (docker containers etc)
- Login
- Submit forms (if able to do so)
- Navigate to /tasks
- Enter the name of the …
=> COP-2810 Search by task name

client/src/App.jsx, client/src/components/form/DisplayForm.jsx, client/src/index.jsx, client/src/utils/StaffIdContext.js, client/src/utils/StaffIdContext.test.js, client/src/utils/hooks.js, client/src/utils/hooks.test.js, server/src/main/resources/application.yml
This is intended to make all expected context objects and properties available to forms, except `shifthistoryid`. We're aware this is used in some forms and will need to investigate why, because shifts are being dropped. There is one linting exception inline which I will revisit later. We also need to bear in mind for the future that users who have not been through onboarding will not have a `staffid`.
=> Make context objects available to forms

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/TasksListPage.test.jsx, client/src/pages/tasks/components/TaskPagination.jsx, client/src/pages/tasks/components/TaskPagination.test.jsx, client/src/pages/tasks/components/TaskPaginationButton.jsx, client/src/pages/tasks/components/TaskPaginationButton.test.jsx
User should be able to navigate through the tasks list with the pagination
- Removed `useRef` and and `loadMore` from `TasksListPage` as they aren't required for pagination functionality
- Removed load more tasks assertion from `TasksListPage.test`
- Added `TaskPagination` component to `TasksListPage` that is conditionally rendered depending on the number of tasks returned
- Added `TaskPaginationButton` to allow for conditionally disable buttons
- Added assertions to `TaskPagination.text.jsx`, focused on testing if the buttons were correctly disabled under certain circumstances and vice versa
- Format comments
- Login
- If 21+ tasks are already present then navigate to /tasks, if not, you will need to submit forms until this task number is reached
- *You should …
=> COP-2813 Enable pagination on task list pages

client/src/pages/home/index.jsx, client/src/pages/tasks/TasksListPage.jsx
User should see the correct number of tasks assigned to them and their team on the dashboard
- Added extra api call to grab the task count for tasks only assigned to the user
- Login
- Submit an intel referral form
- *You should see on the dashboard, the task count for group tasks has increased by 1 whereas the task count for your assigned tasks has stayed the same*
=> COP-2811 Change dashboard task count requests

client/src/pages/home/index.jsx, client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/components/TaskListItem.jsx, client/src/pages/tasks/components/TaskListItem.test.jsx
Changed the query parameters for the task list and task count. Before this change, tasks that were assigned to a someone else other than the current user were not visible.
=> COP-2811 Change task query parameters

client/src/pages/forms/hooks.js, client/src/pages/forms/hooks.test.jsx
When a form is submitted, if the next task to be done is assigned to the current user, that task(form) should load immediately.
- Added api call to check for tasks and load task page if found
- Added tests
- There is now an error showing related to cash/items/firearms seized but it does not seem to be related to this function so will look at it separately
- Login
- Submit a collect-event-at-border form for Air Passengers
- > on submit you should see the People form load
- Submit an intel-referral form
- > on submit you should be returned to the dashboard with a businessKey
- Check group tasks 
- > you should see the Enhance task for this businessKey (you need /devTesting role)
- Submit a Corona virus form
- > you should be returned to the dashboard with a …
=> COP-3774 : Enable follow on forms to load

client/public/locales/en-GB/translation.json, client/src/pages/reports/ReportsListPage.test.jsx, client/src/pages/reports/components/LogoBar.jsx, client/src/pages/reports/components/LogoBar.scss, client/src/pages/reports/components/LogoBar.test.jsx, client/src/pages/reports/components/PowerBIReport.jsx, client/src/pages/reports/components/PowerBIReport.test.jsx, client/src/pages/reports/components/__snapshots__/LogoBar.test.jsx.snap, client/src/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap, client/src/pages/reports/utils/VisitedPagesContext.js, client/src/pages/reports/utils/VisitedPagesContext.test.js, client/src/pages/reports/utils/embedReport.js, client/src/pages/reports/utils/embedReport.test.js, client/src/pages/reports/utils/onPageChange.js, client/src/pages/reports/utils/onPageChange.test.js, client/src/pages/reports/utils/powerBIService.js, client/src/pages/reports/utils/powerBIService.test.js, client/src/pages/reports/utils/useFetchBranchName.js, client/src/pages/reports/utils/useFetchBranchName.test.js, client/src/utils/TeamContext.js, client/src/utils/constants.js
This is — unusually — in one commit, because so much of it interlinks.
• Separate various Power BI functions/hooks into their own files so that the code is more modular and allows unit testing
• Move Power BI branch names into constants file
• Remove 'return to reports list' link in favour of new report reload functionality (tweak Sass accordingly)
• Handle user having no team (in this case branch name is not fetched and filters are not set on page change)
• Other more minor refactoring
• Enhance unit tests
=> Refactor Power BI work

client/package-lock.json, client/package.json, client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/TasksListPage.test.jsx, client/src/pages/tasks/components/TaskFilters.jsx, client/src/pages/tasks/components/TaskFilters.test.jsx, client/src/utils/SecureLocalStorage.js
The user should be able to alter task filters options and persist upon refreshing the page
- Add the `secure-ls` package as used in COPv1 UI for local storage
- Added methods to the `SecureLs` class to keep component code concise
- If `TaskListPage` filters have already been set in local storage, those values are used else use the default value specified
- Passed all filter values to `TaskFilter` component in order to correct update the rendered filter selections
- Refactor `TaskListPage` test
- The task filter persistence for group and your tasks are independent of each other
- Login
- Navigate to `/tasks`
- *You should see the task filters set to their defaults 'Oldest due date' and 'Category'*
- Change these filters to other options i.e. 'Highest priority' …
=> COP-4201 Persist task filters

client/src/pages/tasks/TaskPage.jsx, client/src/pages/tasks/TaskPage.test.jsx, client/src/pages/tasks/hooks.js, client/src/pages/tasks/hooks.test.jsx
If there is a follow-on form from a task, and this form is assigned to the current user, it should display
- added follow on form logic to task submit hook
- updated tests for task submit hook
- reviewed why tests were failing for TaskPage:
- - removed the navigation assertion as the navigation now happens in the submit and not from the TaskPage
- - removed click continue button test, discussing with Tom C the expected behaviour and will then implement that
_Scenario One: starting with a new form_
- fill out a collect-event-at-border form with seized items, cash, and firearms
- click 'submit'
> you should see the next form load (this is triggered by the form submit hook)
- complete that form
- click submit
> you should see the next form load (this is triggered by the task submit hook) …
=> COP-2822 Follow on task forms

client/src/pages/tasks/TaskPage.jsx, client/src/pages/tasks/TaskPage.test.jsx, client/src/pages/tasks/components/TaskList.jsx
If the task assignee and current user are the same, then show the form.
If there is no task assignee, do not show the form.
If there task assignee and current user are NOT the same, do not show the form.
- agreed with Tom C that we should remove the 'complete' button as if you can't see the form you should not be completing the task
- added check for assignee === current user
- updated state resets
- moved assignee into state
- removed complete button
- create a task via postman assigned to jennifer.wallace@digital.homeoffice.gov.uk
- create a few more tasks assigned to you or null
- go to your group tasks
- click on the task assigned to Jennifer
>- you should not see a form
- go back
- click on a task assigned to you
>- you should see a form
- go back
- click on a task that is unclaimed …
=> COP-2822 Showing/Hiding form based on assignee

client/src/components/header/index.jsx, client/src/components/header/index.scss
Mobile menu should appear, and currently is not
- updated structure to follow GDS guide for nav
- put service name in the logo space as COP does not use a logo, but just keeps service name on the left
- added toggle functions for nav
- open cop-ui in a mobile view
- tap on 'menu'
>- you should see the menu items
- tap on 'profile menu item'
> menu should close and take you to profile page
- try tapping menu on various pages
> menu should open/close on tap
=> COP-3595 Mobile menu not showing

client/package-lock.json, client/package.json
This fixes [an issue](https://github.com/alphagov/govuk-frontend/pull/1879) with the `skip-link` component.
=> Update govuk-frontend to latest version

client/src/routes/index.js, client/src/routes/route.test.js
This is being added so we don't need to edit forms that are shared by both UIs but which link to other forms. I'll add a ticket for us to remove this route and update forms once we've migrated.
=> Temporarily add alternative form route

client/src/components/form/DisplayForm.jsx
A number of forms and processes refer to the `processContext` property however this has not been implemented in cop-ui such that it is passed to forms and bpmns correctly. The PR adds `processContext` to the `contexts` object which is then passed down to forms
- Login
- Submit intel referral form
- Claim the raised task
- *You should see the date time pre-populated*
- Fill out the rest of the enhance intel form
- *You should be able to submit the form successfully*
- *There should be no incidents raised in cockpit*
=> COP-4454 Move interpolateContext prop into contexts object

client/src/pages/home/components/Card.jsx
Removed the "title" and "count" id from the `renderTitle` function
- Run cop-ui on localhost
- Login
- Go to dashboard
- *The dashboard should be the same as before*
- *There should be no errors in the console*
=> Remove tag id from dashboard card

client/src/components/form/DisplayForm.jsx, client/src/components/form/DisplayForm.test.jsx
Form error alerts should not persist
DisplayForm to use ErrorAlert rather than AlertBanner
* open collect-event-at-border form
* click next
* click next (without selecting any radio buttons)
> you should see error alerts at the top of the page
* click 'back'
> you should no longer see the error alert box
* open collect-event-at-border form
* click next
* click next without selecting any radio buttons
> you should see error alerts at the top of the page
* select a radio button on the first question
> you should no longer see the error alert for that question at the top of the page
* select a radio button on the second question
> you should no longer see the error alerts
* click next
* click next without answering any questions
* > you should see an error alert at the top of the page
* …
=> COP-4280 Update to use ErrorAlert directly and not through AlertContext/Banner

client/public/locales/en-GB/translation.json, client/src/pages/tasks/TaskPage.test.jsx, client/src/pages/tasks/components/ChangeDueDate.jsx, client/src/pages/tasks/components/ChangeDueDate.test.jsx, client/src/pages/tasks/components/ChangePriority.jsx, client/src/pages/tasks/components/TaskListItem.jsx, client/src/pages/tasks/components/TaskPageSummary.jsx, client/src/pages/tasks/components/TaskPageSummary.test.jsx, client/src/pages/tasks/components/utils.js
User is able to update the due date of an existing task
- Added `ChangeDueDate` component with accompanying test file
- Added tests in `TaskPage.test.jsx` and `TaskPageSummary.test.jsx` to reflect change due date functionality
- Moved commonly used functions into `tasks/components/utils.js` file
- Replaced several instances of the `moment` package with `dayjs` as part of gradual migration
- There is no method for handling invalid due dates in v1, in v2 minor error handling has been added in order to signify an invalid date has been passed
- Login
- Submit form (intel referral or record border event - one that creates a task)
- Go to task created in task list
- Click on task created
- Click on `change` next to the `Due` title
- *You should see a date input and …
=> COP-2824 Add change due date feature

client/src/components/header/Logout.jsx, client/src/components/header/Logout.test.jsx
When a user logs out local storage used by cop-ui should be removed
- Called the `removeAll` method in the `Logout` component
- Added test to `Logout.test.jsx` to check if local storage has been cleared correctly
- Login
- Go to group task list
- Change the task filters to `Latest created date` and `Assignee`
- Refresh page
- *Your task filter selections should persist*
- Go to your task list
- Change the task filters to `Highest priority` and `Priority`
- *Your task filter selections should persist*
- *Dev tools Application local storage should be empty bar i18nextLang*
- Click the `Sign out` button in the header
- Sign back into cop
- Go to group task list
- *Your task filters should be set to `Oldest due date` and `Category`*
- Go to your task list
- *Your …
=> COP-4264 Clear all application local storage on logout

client/src/components/form/hooks.js, client/src/components/form/hooks.test.jsx, client/src/pages/forms/FormPage.jsx, client/src/pages/tasks/TaskPage.jsx
When a user selects 'enter another' (api key `submitAgain`) and submits, another instance of the form, with a new businessKey, should be loaded
- added a `handleOnRepeat` function to FormPage and TaskPage
- updated `hooks.js` submit to check for `handleOnRepeat`
- updated `hooks.jest.js` to test `handleOnRepeat` is called
Covid compliance check is the only form to currently use `submitAgain`
- open Covid Compliance Check form
- open your network tab
- fill out form and tick enter another
- submit
- note the businessKey for the submission
> a new version of the form should load
- fill out the form and do NOT tick enter another
- submit
- note the businessKey for this submission
> the two businessKeys should be different
> you should be taken to the dashboard with a confirmation box
=> COP-4477 Add 'repeat form' functionality

client/src/components/form/DisplayForm.jsx
This fixes the issue of some components not being properly pre-filled in, for example, the COVID form.
=> Fix name of shiftDetailsContext object

server/src/main/resources/application.yml
The user should be able to attach a file without error
- Strips the additional `/files` in the request url sent to the file upload service. 
-  The value of `fileUploadApi.url` has been changed. 
- This change fixes the issue of a 404 being returned by the file upload service due to receiving a request url in this format `/files/files/business-key` however, in local env a 500 is returned which seems to be AWS related. This issue may not exist in dev and so the expected result in the test below would be *Attachment should be successful*
- Once merged, this needs to be tested in dev ASAP
- Login
- Fill out an intel referral form, do not submit form
- Select `Yes` on the `Do you have any files you would like to upload to support this event?` question at the end
- …
=> COP-4642 Strip file service prefix in application.tml

client/src/pages/tasks/TaskPage.jsx
The user should be able to attach a file successfully when completing the record border event process
- Spread the variables property in processContext so that forms have access to the keys they refer to in the forms themselves
- The 'extra' variables property is still included to ensure compatibility is maintained for existing forms or processes that may access values via processContext.variables.ANOTHERKEY
- The change should work in dev without any error being returned by the file upload service
- Login
- Fill out record border event form electing to attach a file prior to submitting form
- Fill out the proceeding forms until you reach the attachments form
- Attach a file with a type in accordance with the ones listed in the form
- *You should receive a 500 …
=> COP-5040 Spread variables property in processContext

client/src/pages/cases/CaseDetailsPanel.jsx, client/src/pages/cases/CasePage.jsx, client/src/pages/cases/CasePage.test.jsx, client/src/pages/cases/CaseResultsPanel.test.jsx, client/src/pages/cases/CasesPage.scss, client/src/pages/cases/CasesResultsPanel.jsx, client/src/pages/cases/components/CaseHistory.jsx, client/src/pages/cases/components/CaseHistory.test.jsx, client/src/pages/cases/components/CaseIntro.jsx, client/src/pages/cases/components/FormDetails.jsx
**AC**
- replicate the behaviour from COP-v1 (cop-private-workflow-tasklist) for the cases page.
**Description**
- This branch adds the case search functionality - a user can search a business key or keyword and search results are displayed in left hand panel. 
- When the user selects a case link the details panel appears. So far, the only sections populated are the heading and the Case History section. 
**To test:** 
- Pull branch and run development server against the Dev environment (change proxy in package json). This is because the workflow-service latest build is still not working and you need to have the latest version of the API to get this to work. 
- Navigate to http://localhost:3000/cases and input a search. Results will appear on the left hand panel if there are hits. Select a …
=> COP-2827+COP-2829: Cases search functionality and history panel

client/src/pages/forms/FormPage.jsx, client/src/pages/forms/Forms.scss
When fields are read only they should be clearly visible as such
- Replicated the styling used in v1
- Made a Forms.scss as per pattern of having scss files for pages/components in their folders
This is not part of GDS yet so must add to our app.
=> COP-4634 Add form styling for disabled fields

client/src/pages/forms/Forms.scss
Replicate v1 styling for v2 forms
Added css to style the grey box to the Forms.scss as it is only used on the one form
v1 used Bootstrap to style this, we do not use Bootstrap in v2 and this style isn't a GDS style so have implemented the simplest styling possible onto the FormBuilder classes that exist
=> COP-4634 Add css for grey box on covid compliance form

client/src/pages/cases/CasesPage.scss
COP uses a 1400px header width, make cases use the same
Added width setting to cases scss file
The standard GDS width style is 900px but we use 1400px on COP. The DP GDS stylesheet keeps to the 900px width so we need to reset that in stylesheets to ensure every page keeps our 1400px width.
=> COP-4634 add styling for case header width

client/public/locales/en-GB/translation.json, client/src/pages/cases/CaseDetailsPanel.jsx, client/src/pages/cases/components/CaseAttachments.jsx, client/src/pages/cases/components/CaseAttachments.test.jsx
User should be able to see case attachments and successfully download them if present
- Added functionality to `CaseAttachments` component
- Added relevant tests for `CaseAttachments` component
- Moved content out of `CaseAttachments` into `translation.json`
- Pull and run cop locally setting the `proxy` in `package.json` to cop-ui dev
SCENARIO 1: 
ON COP-UI DEV:
- Submit `Record border event` form opting to attach file
- Move through to attachment form and attach file with valid file type (keep note of the file you attached)
- Submit form and make note of the business key
ON LOCAL:
- Navigate to cases page and search business key
- Select business key from list
- Scroll down to Case Attachments and click on `View attachments`
- *You should see the file you attached appear in the list*
- …
=> COP-2832 Show case attachments

client/src/components/form/DisplayForm.jsx
The user should be able to submit forms successfully without receiving a 413 error (payload too large).
- Removed `submissionData` from state in `DisplayForm`. The `Form` component has its own `data` object that is updated with each form change and then subsequently validated in the `onChange` handler. This means that the `data` object can be used for `onSubmit` as opposed to the `submissionData` state - the data used in the payload is referred to as `submissionData` but does not refer to state.
- Added `beforeSubmit` hook
- Moved adding of the `form` property to the payload in the `beforeSubmit` hook
- Added removing of context objects (`processContext` and `taskContext`) to the `beforeSubmit` hook
- Testing will need to be done in dev to access process history and double check the …
=> COP-5132 Refactor DisplayForm, remove processContext and taskContext from req payload

client/src/components/form/DisplayForm.jsx
All forms should have access to context variables without error
- Added `hasFormChanged ` state to form component in order for context to be available to the form
- Pull and run cop locally proxying to dev
- Login
- Open network tab in dev tools
SCENARIO 1:
- Submit first part of `Record border event`
- Select the `submit-form` in the network tab
- Look at the `Request payload`
- *You should not see `processContext` and `taskContext` in the payload*
- *You should see other context objects in the payload*
SCENARIO 2:
- Select `Submit Intelligence referral` form
- *On the first question, you SHOULD see the `What type of information do you want to report?` question*
- Submit first part of `Submit Intelligence referral`
- Select the second `submit-form` in the network tab
- Look at the …
=> COP-5132 Add comments hasFormChanged state

client/src/components/form/DisplayForm.jsx, client/src/components/form/DisplayForm.test.jsx
Forms should not add `keycloakContext` and `staffDetailsDataContext` to the request payload
- Add test for context removal in `DisplayForm`
- For further evidence of the context objects not existing in submission, cockpit can also be used to check the payload from each form that exists in camunda
- Login 
- Open network tab in dev tools
- Submit a form (a form that creates a task and does not end straight away i.e. intel ref, record border event )
- *Your form should submit successfully*
- Click on the `submit-form` request in the network tab
- Inspect the `Request Payload`
- *You should NOT see `keycloakContext` and `staffDetailsDataContext` in the payload*
=> COP-3935 Remove context objects on form submission

client/src/pages/cases/CasePage.jsx, client/src/pages/cases/CasePage.test.jsx, client/src/pages/cases/CasesResultsPanel.jsx, client/src/pages/cases/components/FormDetails.jsx, client/src/setupTests.js
When a user clicks a link to a case from a task page make the case open
- the url will have the case ID in it so achieving the AC also achieves the link click from an email and from a direct paste
- added a call to the getCaseDetails function on load when there is a new caseId (businessKey) in the url
- go to your or team `tasklist`
- click on a task
- click on the businessKey link at the top of the page
> you should be taken to the Cases page, with the case loaded for the businessKey you clicked on
- search for a case
> you should no longer see the case that was on the page 
> you should see search results (make sure you've searched for something you know will return results)
- click on a search result
> you should see the Case for this businessKey
=> COP-5249 Enable case loading when URL has caseId

client/src/pages/forms/FormPage.jsx
Some forms seem to be caching data after submit, and then pre-filling the form with that -- make it stop.
It seems to be linked to the `existingSubmission` prop on `DisplayForm`.
Within that we have a `<Form>` component that we pass `submission` to -> and that `submission` uses `existingSubmission` to create it's data.
If you pass nothing to `submission` then FormIO seems to have stored previous answers in a cache/context/state/something (not sure where it's storing it) & populates the form with that.
However, if you pass an empty object then it respects the empty object and does not populate stale data.
For Tasks, we were passing `formSubmission` as `existingSubmission` because there were details to be passed
For Forms, we weren't passing anything which seems to be the issue.
Added an …
=> COP-3840 Add empty object for existingSubmission

client/src/components/alert/ApiErrorAlert.jsx, client/src/components/alert/ApiErrorAlert.test.jsx, client/src/pages/cases/CasePage.test.jsx, client/src/setupTests.js
When the user tries to access a form that does not exist, they should receive a `Page not found` error - as seen in v1. When the user navigates away from the erroring page, the error should NOT persist
- Removed 404 from switch statement in `ApiErrorAlert` and handle rendering `NotFound` independent of the other API errors
- Added history listener into `ApiErrorAlert` that fires when the url changes which in turn sets the `AlertContext` to null
- When `ApiErrorAlert` component unmounts the url listener is removed as it is not required when no errors are present
- Altered and added assertions to `ApiErrorAlert` to account for changes
- Pull and run cop locally pointing the proxy to the dev environment
- Login
- Navigate to the form list
- Add a random string to the end of the url e.g …
=> COP-4924 Form not found throwing 404 instead of page not found message

client/src/components/form/DisplayForm.jsx, client/src/components/form/hooks.js, client/src/pages/forms/FormPage.jsx, client/src/pages/home/index.jsx
On forms, if you refresh, any fields you've already filled in will persist so you don't need to start again.
- index.js to clear all form related storage when you return home (to Dashboard)
- displayForm to store form details on Change
- displayForm to retrieve details if they exist on pageLoad
- hooks.js, FormPage, and displayForm to handle repeatForms where we do not want fields to persist on submit, but where user will not have returned home between form loads
There is a bug in Scenario 6 below that exists on v1, and v2dev. It is not related to localStorage so will be investigated in another ticket.
- start new form fresh
- enter some fields
- refresh page
> answers should persist
- start new form fresh
- enter some fields
- go to edit my profile
- return to form via back button
> …
=> COP-3973 Persist partially filled forms

client/src/components/form/DisplayForm.jsx
In UI1 this data is stored and retrieved per user, because otherwise there’s the possibility that BF users on a shared machine may get fields populated with each other’s data
- added user email to localStorageReference (as is done in v1)
There is a bug in Scenario 6 below that exists on v1, and v2dev. It is not related to localStorage so will be investigated in another ticket.
- start new form fresh
- enter some fields
- refresh page
> answers should persist
- start new form fresh
- enter some fields
- go to edit my profile
- return to form via back button
> answers should persist
- start new form fresh
- enter some fields
- go to dashboard
> answers should NOT persist
- start new form fresh
- enter some fields
- complete the form
- submit the form
- return to form
> answers should not …
=> Add user email to localStorageReference

client/src/components/form/DisplayForm.jsx
Temporary fix as discovered contexts is being lost at form creation. This fix breaks localStorage but we will continue working on that
This reverts the augmentedSubmission object to being created as it was originally, and removes the useEffect that was retrieving from localStorage when available
=> Revert augmentedSubmission

client/src/components/form/DisplayForm.jsx, client/src/pages/cases/components/CaseAction.jsx, client/src/utils/hooks.js
This branch changes the number values in the shiftDetailsContext to strings, to be in line with the data types in v1. See ticket for further details and comparison with v1: https://support.cop.homeoffice.gov.uk/browse/COP-5519. 
In v1, the shiftDetailsContext is defined through the submission of a shift form, which is why the data is in string format. In v2, we are building the context through a call to ref data and using keycloak, so the numbers are type number. To avoid any issues with potential type errors, the hook setting team context has been updated along with the location ID in DisplayForm and CaseActions. 
To test: 
- submit a form either on the forms page or in case actions. 
- check the payload or look in cockpit at the submission data. Find the shiftDetailsContext. You will …
=> COP-5519: Differing data types in the shiftDetailsContext object across v1 and v2

client/package-lock.json, client/package.json
Downgrading `formiojs` to version `4.9.19` from version `4.12.4`. Bugs have been introduced with upgraded version of `formiojs`. COP UI v1 is also using version `4.9.19` and so the decision has been made to revert to this version to enable normal form functionality. Downgrading `formiojs` will allow us to test bugs in the backlog to check if they still persist with the older version.
=> COP-5480 Downgrade formiojs to 4.9.19

client/src/components/form/DisplayForm.jsx
The user should be able to cancel from form view and NOT have a confirm box appear
- Removed `async` from `beforeCancel` hook, this hook should not be asynchronous for the purpose of which we are using it
- Pull and run cop locally pointing proxy to dev
- Login
- Navigate to `/forms`
- Select a form
- When the form loads, click the `Cancel` button at the bottom right hand side of the form
- *You should NOT have a confirm box appear*
- *You should be taken to the `/forms` page successfully*
- Repeat this process for several forms
=> COP-5665 Remove async from beforeCancel hook

server/src/main/resources/application.yml
Testing while after a file upload we receive a 500 error - cannot test file uploading locally 
This is setting timeouts on the zuul proxying to test if that is the problem, set to 2min for test
=> Add zuul host timeout to test if timeouts are causing 500 errors

client/package.json, client/public/locales/en-GB/translation.json, client/src/pages/cases/components/CaseIntro.jsx
Description
- Adds functionality to the "Copy case link" button on Cases details panel. 
To test: 
- run locally and go to the Cases page. 
- search for any case and click on one. 
- In the top panel of the Case details panel is the copy button. Click this and then test it has copied to your clipboard.
=> COP-5666: Add copy case link button functionality

client/src/pages/home/index.jsx, client/src/pages/tasks/TasksListPage.jsx
When a user submits a line manager request, they should see a task appear in their own user task list
- Changed `assignee` to `involvedUser` in the camunda API calls for both the users tasks and the dashboard count. Assignee only picked up tasks with the current user assigned to it whereas `involvedUser` includes user associated tasks - not just assignee related
- Pull and run cop locally pointing the proxy to the dev environment
- Login
- Navigate to `/submit-a-form/set-or-change-line-manager`
- Working with another user, input that user email address and submit form
- *The form should submit successfully*
- *The other user should receive an email in regards to this event*
- Ask the other user to navigate to their `tasks/your-tasks`
- *They should see the line manager event in their list …
=> COP-5468 Modify task requests for homepage and user tasks

client/src/pages/cases/components/CaseAction.jsx
When a user submits a case action, all context related properties should be resolved correctly.
- Passed `submission` prop with the `contexts` object down to the `Form` component
- As a result of passing `submission`, context now needs to be removed in the `beforeSubmit`
- Removed `showSubmissionConfirmation` in `setTimeout` to avoid state updates after unmounting
- With the downgrade of `formiojs`, bugs in the `Form` component are not present i.e. allowing us to pass a `submission` prop down without the object being passed down overwriting key values unexpectedly.
- Pull and run cop locally pointing proxy to dev environment
- Login
- Submit form that generates multiple case actions
- Go to case that has been created
- Open the network tab in dev tools
- Submit a `Record action` form
- …
=> COP-5475 Add context to hidden component for case actions

client/src/pages/tasks/TaskPage.jsx
Understand & fix `existingSubmission` as it is prefilling data on forms in unexpected ways
`TaskPage` was always passing through `existingSubmission` as `undefined`. Determined that based on the current code, it would always be undefined
Removed code that was resulting in undefined
Updated get call to simplify it to only retrieving form information and determining whether to display form or not
The assignee label breaks with this PR, the logic for which name to show is being moved and will be added in the next PR
Scenario 1 : follow on forms
- start a collect-event-at-border form
- click submit
- > you should be taken to the next followon form
- complete that form and click submit
- > you should be taken to the next followon form
Scenario 2
- fill out and submit an intel referral form
- …
=> COP-5557 Refactor TaskPage

client/src/components/form/DisplayForm.jsx, client/src/components/form/hooks.js, client/src/pages/forms/FormPage.jsx, client/src/pages/tasks/TaskPage.jsx
On forms, if you refresh, any fields you've already filled in will persist so you don't need to start again.
- FormPage & TaskPage now create their `localStorageReference` and pass that down to DisplayForm
- DisplayForm checks for localStorage and merges that with `context` to create `augmentedSubmission`
- Clear localStorage for the form submitted on submission
- start new form fresh
- enter some fields
- refresh page
> answers should persist
- start new form fresh
- enter some fields
- go to edit my profile
- return to form via back button
> answers should persist
- start new form fresh
- enter some fields
- go to dashboard
> answers should NOT persist
- start new form fresh
- enter some fields
- complete the form
- submit the form
- return to form
> answers should not persist
- open a …
=> COP-5730 Update localStorage storing/deleting for persisting form data

client/src/pages/tasks/TasksListPage.jsx
The task list page reflects the same behaviour as v1 when clicking on next page of tasks
- Added `setData` at the beginning of the `useEffect` that fetches task data rendering the spinner for each task list query
- Pull and run cop locally pointing proxy to dev environment
- Login
- Go to group task list page
- Click on next pagination button at the bottom of task list
- *You should see an application spinner and then the new task list is rendered*
- Click on last pagination button at the bottom of the task list
- *You should see an application spinner and then the new task list is rendered*
=> Add loading spinner for next page task

client/package-lock.json, client/package.json
Due to later versions of formiojs causing errors (ticket open to investigate and safely update), we want to ensure the app only uses 4.9.19 for now
=> Force use of formiojs version 4.9.19

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/TasksListPage.test.jsx
When a user searches for a task by name, the application spinner should only render in the TaskList and not remove the task filters and task count
- Removed the initial `setData` from the `useEffect`.
- Added `areTasksLoading` state in order to conditionally render application spinner child components of `TaskListPage` (`TaskList` and `TaskPagination`)
- Added tests to `TaskListPage`
As a result of the initial `TaskListPage` design, the application spinner was being rendered for every data change in replacement of the task filters and count. This meant when a user searched for a task, each change would result in the spinner rendering over the search bar until the new tasks were returned (essentially, type one letter and spinner appears with search bar being removed). In order to …
=> Fix application spinner rendering over whole task list page on state change

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/components/TaskFilters.jsx, client/src/pages/tasks/components/TaskFilters.test.jsx
When a user filters the task list by sort or search, the task list returned should start at page index of 0. When filtering by groups, the page index should remain the same.
- Moved task filtering logic into `TaskFilters` component (not inc. the api call made as a result)
- Split the filtering out from 1 function into 3 separate ones for clarity and to handle specific scenarios required for each filter type
- Updated tests to reflect changes
To verify for testing, have the network tab open and double check that network requests are only made for both sort and search but NOT for groups
- Pull and run cop locally pointing the proxy to the dev environment
- Login
- Navigate to `/tasks`
- Click 'Next' on the pagination buttons at the bottom of the list
- *You should be taken to next page of …
=> COP-5799 Reset page number to 0 when task filtering has occurred

client/public/locales/en-GB/translation.json, client/src/pages/cases/CasePage.jsx
This branch updates the search functionality for Cases by stripping any " symbols from the search string. This is because the v2 Cases API throws a 500 if you search using a search term with unclosed double quotes e.g. "COP-123 ... 
On v1, users are guided to search using double quotes as this is what the old engine required. No quotes are required on v2 to return the correct cases but users will likely be used to searching in this way, so here we add in logic to strip out all " from the search input to avoid returning 500 errors. 
Also updated the hint to remove reference to searching with quote marks. 
- Run locally and point proxy to dev. 
- Navigate to Cases page and try to search for a case with double quotes in. You should see no errors.
=> Strip quote marks from Case Search input

client/package-lock.json, client/package.json
Update formio-gds-templates package to latest patch as this corrects a heading size
- delete your `node_modules` & `package-lock.json`
- run `npm i` from `\client`
- go to an intel case
- view the `record check` form
- > titles should look size relevant and not be h1 sized
=> Bump package patches

client/src/components/form/DisplayForm.jsx, client/src/components/form/DisplayForm.test.jsx
If we try to perform validation that depends on certain context objects which are removed when the form is submitted, we run into a problem when the `beforeSubmit` hook is used in that they are removed before the validation occurs. If we instead use the `customValidation` hook then these objects are removed _after_ validation occurs, getting around the problem.
=> Use customValidation instead of beforeSubmit hook

client/src/App.jsx
When a user is using COP, the keycloak token used for axios requests shall remain valid for as long as the refreshToken permits. When the refreshToken is no longer valid, the user should be logged out gracefully. 
- Added `onTokenExpired` listener `App.jsx`, this listens for when the token expires then executes the custom function assigned to it. 
- When the refreshToken is no longer valid (when the token can no longer be updated), the `catch` should be triggered and the user logged out
- Pull and run cop locally pointing proxy to dev environment
- Login
- Open network tab in dev tools
- Refresh page
- *You should see a `token` request made in the network tab*
- Wait for the amount of time the current token is valid for (env dependent), occasionally registering activity on your machine …
=> COP-5904 Add token expiration handler

client/src/pages/tasks/components/ChangeDueDate.test.jsx
A decision is yet to be made regarding what times are rendered in the UI and what is stored in the database. As such, the test of time equality in ChangeDueDate has been removed where only testing the change in day, month and year is tested. A ticket will be raised to investigate this further.
=> Remove time comparison from ChangeDueDate test

client/src/components/form/hooks.js, client/src/components/form/hooks.test.jsx, client/src/pages/forms/FormPage.jsx, client/src/pages/tasks/TaskPage.jsx, client/src/utils/constants.js
**Intro**
This PR contains 3 commits to fix 2 issues with the Man Dec process. The 2 issues are that the form data can't be found in the process which is fixed by commit 1 and that the encryption of task data is failing which is fixed by commit 3. Commit 2 is a task to tidy the submit paths so they can be better reused in commit 3.
**1. Update submitForm hook to make the key for the form data in the payload dynamic**
This follows what is done in V1 and enables the form data in the payload to be named differently from the form name by checking if a submitVariableName hidden field is present in the form and if so then using it's value as the data key rather than the form name.
This gives us the ability to use the form name for other things such as form versioning, which was started to be …
=> COP-5750 - ManDec: Cannot find 'startDeclaration' on COPv2

client/src/pages/tasks/TasksListPage.jsx, client/src/pages/tasks/components/TaskList.jsx, client/src/pages/tasks/components/TaskList.test.jsx, client/src/pages/tasks/components/TaskListItem.jsx, client/src/pages/tasks/components/TaskListItem.test.jsx
This branch updates the "Tasks Assigned to you" page to reflect the format of V1. Full details of the discrepancy are found here: https://support.cop.homeoffice.gov.uk/browse/COP-6752
**To Test:**
- pull and run locally pointing proxy to dev
- navigate to "Tasks assigned to you page" via the dashboard. If you don't have any tasks you'll need to create one (complete a Record Border Event form to trigger task)
- You should now see an "Action" button rather than Claim/Unclaim and the page should now look the same as V1
-  Clicking Action will take you to the Task Page where you can complete the task
=> COP-6752: Update tasks assigned to you page to be same as v1

client/src/components/form/DisplayForm.jsx, client/src/pages/cases/components/CaseAction.jsx
This branch updates the `shiftDetailsContext` object which is used to append data onto the form submissions that are subsequently used in the BPMNs. It changes the `team` value to be equal to the `currentGroup`. This change is a temporary fix to avoid having to change a large number of BPMNs which are currently set to look for shiftDetailsContext.team.code, so instead team.code will now be equal to currentGroup.code. 
**To test**
- run locally and point the proxy to dev
- you need to have multiple groups associated with your profile to test fully.
- On the dashboard, change your current group to something else other than the one you logged in as (i.e. not your default team). 
- Go to Forms list page and complete a Collect Event at Border up until a task is triggered. 
- Navigate back to …
=> COP-7229: Add temp fix to set team equal to currentGroup in shiftDetailsContext

client/src/utils/CurrentGroupContext.jsx, client/src/utils/hooks.js
This branch updates the Current Group context to store the currentGroup in local storage, rather that secure local storage. This is to fix a bug where by the encryption/decrytion of the current group object was cause V2 UI to break in certain circumstances. 
**To test:**
- run v2 locally with proxy pointing to dev
1. Submit the Report a Variance form
2. Go to tasks and click "Action" on the newly created one
3. Click the link on the first page of the form: 
"To complete this form, you will need to review the case history (opens in new tab)."
4. Navigate back to first window and complete the form
5. Go back to task list, click on Action on the OTHER task the workflow triggered.
6. Click the link on the first page: "To complete this form, you will need to review the case history (opens in …
=> COP-7110: COP v2 showing blank page [local storage issue]

client/public/locales/en-GB/translation.json, client/src/pages/home/index.jsx
This branch changes the error message for when a user doesn't have a team set up on keycloak telling them how to reach support link.
To test:
- delete your team on my profile page (or via keycloak)
- log out and in again. You should see the correct error message. You will then have to add your team back in (ask me or dev ops to do this)
=> COP-7382: Change no team set error message

client/src/components/form/DisplayForm.jsx, client/src/components/form/DisplayForm.test.jsx, client/src/pages/forms/FormPage.jsx, client/src/pages/forms/FormPage.test.jsx
User Profile form dispatches this event - when it does we should return the user to the dashboard.
=> Handle 'cancel-form' custom event

client/src/App.jsx, client/src/components/header/Logout.jsx
This branch adds function to clear currentGroup from local storage when a user logs out, or if keycloak refresh token fails and user is automatically logged out. 
This is to prevent a bug where a previous user's currentGroup persists in localstorage when a new user logs in.
=> COP-7449: Team group local storage is not restricted to the user

client/src/components/header/index.jsx, client/src/components/header/index.test.jsx
We're avoiding using Navi for this link as we want COP to refresh so that a new Keycloak token is fetched for the user and they can more quickly see their details refreshed (as in V1).
=> Use direct link to User Profile form

client/src/pages/cases/components/CaseAction.jsx, client/src/pages/cases/components/CaseAction.test.jsx, client/src/pages/cases/utils/LatestFormDataPath.js, client/src/pages/cases/utils/LatestFormDataPath.test.js, client/src/utils/constants.js
This change adds the append a record functionality required by Operating Mandate.
It presents the Operating Mandate Request and Ncc Upate Review Date/Time forms as Case Actions in Case View pre-populated with the latest data and enables the user to make changes to the submitted data.
Once the changed data has been submitted the data is available to view in the Case History as a new form. This keeps a history of each of the submitted form payloads so it's possible to see what was changed, when and by who.
This append a record functionality is opt-in so it doesn't affect any existing Case Action forms.
This change also handles the Cancel button so the form is reset to its initial state.
=> COP-7244 - Operating Mandate - Append a Record in V2

client/src/pages/cases/components/FormDetails.jsx
Update `FormDetails` to display form data correctly in different forms
Previously it was possible to open all the forms for a process in the Case History section of Case View at the same time and doing so would populate all the open forms with the data from the last form that was opened. 
This is now fixed so that only one form for a process can be opened at a time and that form displays the correct data.
=> COP-7538 - V2 Operating Mandate - Case history is not showing the resubmitted form data.

client/public/locales/en-GB/translation.json, client/src/components/layout/index.jsx, client/src/components/layout/index.test.jsx, client/src/pages/forms/FormPage.jsx, client/src/pages/forms/FormPage.test.jsx
This branch adds in a "Back to forms" list link on an individual form page and changes the site wide back button to read "back to dashboard". This is to make the UI more accessible in-line with V1 as described in ticket COP-7139. It also updates the tests accordingly. 
*To test:*
- Run locally pointing at the dev proxy.
- Navigate to the Forms list page, you will see one link back to the Dashboard. Test this works as expected.
- Navigate to the Forms list page and then click on any form to start it. You will see a link at the top of the page back to the dashboard AND the forms page. Test both of these work as expected. 
- Tests updated for these changes (npm test)
=> COP-7139: Add in back to dashboard and back to forms link for accessibility

client/src/pages/cases/components/FormDetails.jsx, client/src/pages/cases/components/FormDetails.test.jsx
**Description**
This branch fixes a bug where "Latest" label is showing for all form instances under the Case History section on the Cases page. It puts the forms in the correct submission date order (from latest to oldest) and adds the Latest label for only the latest instance. It also updates the tests for this change. 
**To test**
- Run branch locally pointing proxy to dev. 
- Navigate to cases page. Search for a case which you know has multiple completed forms (e.g. http://localhost:3000/cases/DEV-20210628-1460). Go to Case History tab and select drop down that contains multiple forms (for this example, "Collect Event at Border" at the bottom).
- Click on the Form links one by one to open them. You will see they are now in the correct order with Latest first and a Latest Label on only …
=> COP-7650: Update Case History section so forms display in order with correct Latest label
